
/* IMPORTS */

// Library imports
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var mongoose = require('mongoose');

// Routes
var index = require('./routes/index');

// Express init
var app = express();

/* SETUP DATABASE USAGE */

// connect to MongoDB
mongoose.Promise = global.Promise;
var mongoURL = '127.0.0.1:27017';
mongoose.connect('mongodb://' + mongoURL + '/CleanIT')
  .then(() =>  console.log('connection succesful'))
  .catch((err) => console.error(err));


/*** AUTOGENERATED START ***/

/* SETUP JADE ENGINE */
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// TODO: Uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

/*** AUTOGENERATED END ***/

/* SETUP ROUTES */
var devices = require('./services/devices');

app.use('/', index);
app.use('/devices', devices);

/* ERROR HANDLING */

// Catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

app.use(function(err, req, res, next) {
  // Locals are providing errors for development purpose only
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // Render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
